services:
    mybuilder.cronos_bundle.annotation_cron_exporter:
        class: MyBuilder\Bundle\CronosBundle\Exporter\AnnotationCronExporter
        public: true
        arguments:
            - "@annotation_reader"
        calls:
            - [ setConfig, ["%mybuilder.cronos_bundle.exporter_config%"] ]

    mybuilder.cronos_bundle.command.dump:
        class: MyBuilder\Bundle\CronosBundle\Command\DumpCommand
        tags:
            - { name: 'console.command' }

    mybuilder.cronos_bundle.command.replace:
        class: MyBuilder\Bundle\CronosBundle\Command\ReplaceCommand
        tags:
            - { name: 'console.command' }

    mybuilder.cronos_bundle.cron_process_updater:
        class: MyBuilder\Cronos\Updater\CronUpdater
        public: true
        arguments: [ "@mybuilder.cronos_bundle.cron_manipulator" ]

    mybuilder.cronos_bundle.cron_manipulator:
        class: MyBuilder\Cronos\Updater\CommandCronManipulator
        arguments:
            - "@mybuilder.cronos_bundle.process_runner"
            - "@mybuilder.cronos_bundle.filesystem"
        public: false

    mybuilder.cronos_bundle.process_runner:
        class: MyBuilder\Cronos\Updater\SymfonyProcessRunner
        public: false

    mybuilder.cronos_bundle.filesystem:
        class: MyBuilder\Cronos\Updater\SymfonyFileSystem
        public: false
